version: '2.1'
services:
  vault:
    image: dq
    ports:
      - 8200:8200
    volumes:
      - /var/vault:/var/lib/vault
      - /var/log:/var/log
      - ./vault.hcl:/etc/vault.d/vault.hcl
    command:
      - vault
      - server
      - -config=/etc/vault.d/vault.hcl
      - -log-level=info
    cap_add:
      - IPC_LOCK
    env_file: ['.env']
